name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
        - name: Login
  uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build
   uses: okteto/actions/build@v1
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}
